### PR TITLE
Adds the ability to query and post intents information to API.ai.

### PR DESCRIPTION
**Pull request by bramski**
This adds ```intentsRequest``` so that this API can be used to talk to ```/intents```.

### CODE REVIEW

**Comment by sstepashka** [comment]
Hi bramski,

Our SDKs are designed as tools for easy processing of query requests and responses. We are not planning to extend this functionality in the nearest future.

For other operations, you can use our endpoints. You can find the information about all currently available endpoints here: https://docs.api.ai/docs/reference#resources

I think it should be another library. Development and CLient instructions should be splitted.

**Comment by bramski** [comment]
Why don't you open up a development SDK and I can contribute to that?  As
someone starting out using your API the distinction between the two is
totally unclear.  It's the same API servers and the only difference is the
used token.  In fact there is no error if you use the client token on the
dev specific endpoints.  You can get the intents, and you can issue a PUT
and receive a 200 but the operation is ignored.

**Comment by sstepashka** [comment]
This is part about development agent, the library uses only for client version. Access to intents through "client access token" is bug, its should be able only through development agent. And it will be fixed soon.

**Comment by bramski** [comment]
Seemed like a bug to me.

So you don't have an sdk for the developer endpoints?  This repo and the
package are then misnamed as this is just the api-ai-client sdk.  You can't
really blame me for using it for this purpose and for opening a PR.  It
simply looked like missing functionality and this is an open source project.

This does appear to be what you guys are providing for the api-ai node sdk
am I right?

**Comment by sstepashka** [comment]
Maybe in future we will inplement module for agent entities CRUD, but not now. All manipulations of agent data should be hide under development token.

**Comment by siryoav** [comment]
I am totally with @bramski . I started looking at this SDK for the automatic handling of intents, agents and entities. Well the moment I saw Entities - I thought it is the right SDK, and that I will have to go through documentation to understand how to create intents or agents.
This is very misleading Repo.
Also, I strongly  recommend you to open Development SDK for people like me.

**Pull request closed without merging**
